import type { Metadata } from "next";
import "./globals.css";
import { SessionAuthProvider } from "@/components/session.auth";
import {Toaster} from "sonner"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body

      >
        <SessionAuthProvider>
        <Toaster duration={2500}/>
        {children}
        </SessionAuthProvider>
      </body>
    </html>
  );
}
